/*
 * Xero Accounting API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: api@xero.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.xero.models.accounting;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.xero.api.StringUtil;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;
import java.util.UUID;

/** BankTransferDelete */
public class BankTransferDelete {
  StringUtil util = new StringUtil();

  @JsonProperty("BankTransferID")
  private UUID bankTransferID;

  @JsonProperty("Status")
  private String status = "DELETED";

  /**
   * The Xero identifier for a bank transfer
   *
   * @param bankTransferID UUID
   * @return BankTransferDelete
   */
  public BankTransferDelete bankTransferID(UUID bankTransferID) {
    this.bankTransferID = bankTransferID;
    return this;
  }

  /**
   * The Xero identifier for a bank transfer
   *
   * @return bankTransferID
   */
  @ApiModelProperty(required = true, value = "The Xero identifier for a bank transfer")
  /**
   * The Xero identifier for a bank transfer
   *
   * @return bankTransferID UUID
   */
  public UUID getBankTransferID() {
    return bankTransferID;
  }

  /**
   * The Xero identifier for a bank transfer
   *
   * @param bankTransferID UUID
   */
  public void setBankTransferID(UUID bankTransferID) {
    this.bankTransferID = bankTransferID;
  }

  /**
   * The status of the bank transfer.
   *
   * @param status String
   * @return BankTransferDelete
   */
  public BankTransferDelete status(String status) {
    this.status = status;
    return this;
  }

  /**
   * The status of the bank transfer.
   *
   * @return status
   */
  @ApiModelProperty(required = true, value = "The status of the bank transfer.")
  /**
   * The status of the bank transfer.
   *
   * @return status String
   */
  public String getStatus() {
    return status;
  }

  /**
   * The status of the bank transfer.
   *
   * @param status String
   */
  public void setStatus(String status) {
    this.status = status;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankTransferDelete bankTransferDelete = (BankTransferDelete) o;
    return Objects.equals(this.bankTransferID, bankTransferDelete.bankTransferID)
        && Objects.equals(this.status, bankTransferDelete.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bankTransferID, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BankTransferDelete {\n");
    sb.append("    bankTransferID: ").append(toIndentedString(bankTransferID)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
