/*
 * Xero Accounting API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: api@xero.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.xero.models.accounting;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.xero.api.StringUtil;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

/** BudgetLine */
public class BudgetLine {
  StringUtil util = new StringUtil();

  @JsonProperty("AccountID")
  private UUID accountID;

  @JsonProperty("AccountCode")
  private String accountCode;

  @JsonProperty("BudgetBalances")
  private List<BudgetBalance> budgetBalances = new ArrayList<BudgetBalance>();
  /**
   * See Accounts
   *
   * @param accountID UUID
   * @return BudgetLine
   */
  public BudgetLine accountID(UUID accountID) {
    this.accountID = accountID;
    return this;
  }

  /**
   * See Accounts
   *
   * @return accountID
   */
  @ApiModelProperty(value = "See Accounts")
  /**
   * See Accounts
   *
   * @return accountID UUID
   */
  public UUID getAccountID() {
    return accountID;
  }

  /**
   * See Accounts
   *
   * @param accountID UUID
   */
  public void setAccountID(UUID accountID) {
    this.accountID = accountID;
  }

  /**
   * See Accounts
   *
   * @param accountCode String
   * @return BudgetLine
   */
  public BudgetLine accountCode(String accountCode) {
    this.accountCode = accountCode;
    return this;
  }

  /**
   * See Accounts
   *
   * @return accountCode
   */
  @ApiModelProperty(example = "90.0", value = "See Accounts")
  /**
   * See Accounts
   *
   * @return accountCode String
   */
  public String getAccountCode() {
    return accountCode;
  }

  /**
   * See Accounts
   *
   * @param accountCode String
   */
  public void setAccountCode(String accountCode) {
    this.accountCode = accountCode;
  }

  /**
   * budgetBalances
   *
   * @param budgetBalances List&lt;BudgetBalance&gt;
   * @return BudgetLine
   */
  public BudgetLine budgetBalances(List<BudgetBalance> budgetBalances) {
    this.budgetBalances = budgetBalances;
    return this;
  }

  /**
   * budgetBalances
   *
   * @param budgetBalancesItem BudgetBalance
   * @return BudgetLine
   */
  public BudgetLine addBudgetBalancesItem(BudgetBalance budgetBalancesItem) {
    if (this.budgetBalances == null) {
      this.budgetBalances = new ArrayList<BudgetBalance>();
    }
    this.budgetBalances.add(budgetBalancesItem);
    return this;
  }

  /**
   * Get budgetBalances
   *
   * @return budgetBalances
   */
  @ApiModelProperty(value = "")
  /**
   * budgetBalances
   *
   * @return budgetBalances List<BudgetBalance>
   */
  public List<BudgetBalance> getBudgetBalances() {
    return budgetBalances;
  }

  /**
   * budgetBalances
   *
   * @param budgetBalances List&lt;BudgetBalance&gt;
   */
  public void setBudgetBalances(List<BudgetBalance> budgetBalances) {
    this.budgetBalances = budgetBalances;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BudgetLine budgetLine = (BudgetLine) o;
    return Objects.equals(this.accountID, budgetLine.accountID)
        && Objects.equals(this.accountCode, budgetLine.accountCode)
        && Objects.equals(this.budgetBalances, budgetLine.budgetBalances);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountID, accountCode, budgetBalances);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BudgetLine {\n");
    sb.append("    accountID: ").append(toIndentedString(accountID)).append("\n");
    sb.append("    accountCode: ").append(toIndentedString(accountCode)).append("\n");
    sb.append("    budgetBalances: ").append(toIndentedString(budgetBalances)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
