/*
 * Xero Accounting API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: api@xero.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.xero.models.accounting;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.xero.api.StringUtil;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** GetPurchaseOrdersResponse */
public class GetPurchaseOrdersResponse {
  StringUtil util = new StringUtil();

  @JsonProperty("Id")
  private String id;

  @JsonProperty("Status")
  private String status;

  @JsonProperty("ProviderName")
  private String providerName;

  @JsonProperty("DateTimeUTC")
  private String dateTimeUTC;

  @JsonProperty("PageInfo")
  private PageInfo pageInfo;

  @JsonProperty("PurchaseOrders")
  private List<PurchaseOrder> purchaseOrders = new ArrayList<PurchaseOrder>();
  /**
   * id
   *
   * @param id String
   * @return GetPurchaseOrdersResponse
   */
  public GetPurchaseOrdersResponse id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   *
   * @return id
   */
  @ApiModelProperty(value = "")
  /**
   * id
   *
   * @return id String
   */
  public String getId() {
    return id;
  }

  /**
   * id
   *
   * @param id String
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * status
   *
   * @param status String
   * @return GetPurchaseOrdersResponse
   */
  public GetPurchaseOrdersResponse status(String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   *
   * @return status
   */
  @ApiModelProperty(value = "")
  /**
   * status
   *
   * @return status String
   */
  public String getStatus() {
    return status;
  }

  /**
   * status
   *
   * @param status String
   */
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   * providerName
   *
   * @param providerName String
   * @return GetPurchaseOrdersResponse
   */
  public GetPurchaseOrdersResponse providerName(String providerName) {
    this.providerName = providerName;
    return this;
  }

  /**
   * Get providerName
   *
   * @return providerName
   */
  @ApiModelProperty(value = "")
  /**
   * providerName
   *
   * @return providerName String
   */
  public String getProviderName() {
    return providerName;
  }

  /**
   * providerName
   *
   * @param providerName String
   */
  public void setProviderName(String providerName) {
    this.providerName = providerName;
  }

  /**
   * dateTimeUTC
   *
   * @param dateTimeUTC String
   * @return GetPurchaseOrdersResponse
   */
  public GetPurchaseOrdersResponse dateTimeUTC(String dateTimeUTC) {
    this.dateTimeUTC = dateTimeUTC;
    return this;
  }

  /**
   * Get dateTimeUTC
   *
   * @return dateTimeUTC
   */
  @ApiModelProperty(value = "")
  /**
   * dateTimeUTC
   *
   * @return dateTimeUTC String
   */
  public String getDateTimeUTC() {
    return dateTimeUTC;
  }

  /**
   * dateTimeUTC
   *
   * @param dateTimeUTC String
   */
  public void setDateTimeUTC(String dateTimeUTC) {
    this.dateTimeUTC = dateTimeUTC;
  }

  /**
   * pageInfo
   *
   * @param pageInfo PageInfo
   * @return GetPurchaseOrdersResponse
   */
  public GetPurchaseOrdersResponse pageInfo(PageInfo pageInfo) {
    this.pageInfo = pageInfo;
    return this;
  }

  /**
   * Get pageInfo
   *
   * @return pageInfo
   */
  @ApiModelProperty(value = "")
  /**
   * pageInfo
   *
   * @return pageInfo PageInfo
   */
  public PageInfo getPageInfo() {
    return pageInfo;
  }

  /**
   * pageInfo
   *
   * @param pageInfo PageInfo
   */
  public void setPageInfo(PageInfo pageInfo) {
    this.pageInfo = pageInfo;
  }

  /**
   * purchaseOrders
   *
   * @param purchaseOrders List&lt;PurchaseOrder&gt;
   * @return GetPurchaseOrdersResponse
   */
  public GetPurchaseOrdersResponse purchaseOrders(List<PurchaseOrder> purchaseOrders) {
    this.purchaseOrders = purchaseOrders;
    return this;
  }

  /**
   * purchaseOrders
   *
   * @param purchaseOrdersItem PurchaseOrder
   * @return GetPurchaseOrdersResponse
   */
  public GetPurchaseOrdersResponse addPurchaseOrdersItem(PurchaseOrder purchaseOrdersItem) {
    if (this.purchaseOrders == null) {
      this.purchaseOrders = new ArrayList<PurchaseOrder>();
    }
    this.purchaseOrders.add(purchaseOrdersItem);
    return this;
  }

  /**
   * Get purchaseOrders
   *
   * @return purchaseOrders
   */
  @ApiModelProperty(value = "")
  /**
   * purchaseOrders
   *
   * @return purchaseOrders List<PurchaseOrder>
   */
  public List<PurchaseOrder> getPurchaseOrders() {
    return purchaseOrders;
  }

  /**
   * purchaseOrders
   *
   * @param purchaseOrders List&lt;PurchaseOrder&gt;
   */
  public void setPurchaseOrders(List<PurchaseOrder> purchaseOrders) {
    this.purchaseOrders = purchaseOrders;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetPurchaseOrdersResponse getPurchaseOrdersResponse = (GetPurchaseOrdersResponse) o;
    return Objects.equals(this.id, getPurchaseOrdersResponse.id)
        && Objects.equals(this.status, getPurchaseOrdersResponse.status)
        && Objects.equals(this.providerName, getPurchaseOrdersResponse.providerName)
        && Objects.equals(this.dateTimeUTC, getPurchaseOrdersResponse.dateTimeUTC)
        && Objects.equals(this.pageInfo, getPurchaseOrdersResponse.pageInfo)
        && Objects.equals(this.purchaseOrders, getPurchaseOrdersResponse.purchaseOrders);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, status, providerName, dateTimeUTC, pageInfo, purchaseOrders);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetPurchaseOrdersResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    providerName: ").append(toIndentedString(providerName)).append("\n");
    sb.append("    dateTimeUTC: ").append(toIndentedString(dateTimeUTC)).append("\n");
    sb.append("    pageInfo: ").append(toIndentedString(pageInfo)).append("\n");
    sb.append("    purchaseOrders: ").append(toIndentedString(purchaseOrders)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
