/*
 * Xero Accounting API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: api@xero.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.xero.models.accounting;
import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.xero.models.accounting.Journal;
import com.xero.models.accounting.ValidationError;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.io.IOException;

import org.threeten.bp.OffsetDateTime;
import org.threeten.bp.LocalDateTime;
import org.threeten.bp.ZoneId;
import org.threeten.bp.Instant;
import org.threeten.bp.LocalDate;
import com.xero.api.StringUtil;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * Journals
 */

public class Journals {
  StringUtil util = new StringUtil();

  @JsonProperty("Warnings")
  private List<ValidationError> warnings = new ArrayList<ValidationError>();

  @JsonProperty("Journals")
  private List<Journal> journals = new ArrayList<Journal>();
  /**
  * Displays array of warning messages from the API
  * @param warnings  List&lt;ValidationError&gt;
  * @return Journals
  **/
  public Journals warnings(List<ValidationError> warnings) {
    this.warnings = warnings;
    return this;
  }

  /**
   * Displays array of warning messages from the API
   * @param warningsItem ValidationError 
   * @return Journals
  **/
  public Journals addWarningsItem(ValidationError warningsItem) {
    if (this.warnings == null) {
      this.warnings = new ArrayList<ValidationError>();
    }
    this.warnings.add(warningsItem);
    return this;
  }

   /**
   * Displays array of warning messages from the API
   * @return warnings
  **/
  @ApiModelProperty(value = "Displays array of warning messages from the API")
  /** 
   * Displays array of warning messages from the API
   * @return warnings List<ValidationError>
  **/
  public List<ValidationError> getWarnings() {
    return warnings;
  }

  /** 
  * Displays array of warning messages from the API
  * @param warnings List&lt;ValidationError&gt; 
  **/

  public void setWarnings(List<ValidationError> warnings) {
    this.warnings = warnings;
  }

  /**
  * journals
  * @param journals  List&lt;Journal&gt;
  * @return Journals
  **/
  public Journals journals(List<Journal> journals) {
    this.journals = journals;
    return this;
  }

  /**
   * journals
   * @param journalsItem Journal 
   * @return Journals
  **/
  public Journals addJournalsItem(Journal journalsItem) {
    if (this.journals == null) {
      this.journals = new ArrayList<Journal>();
    }
    this.journals.add(journalsItem);
    return this;
  }

   /**
   * Get journals
   * @return journals
  **/
  @ApiModelProperty(value = "")
  /** 
   * journals
   * @return journals List<Journal>
  **/
  public List<Journal> getJournals() {
    return journals;
  }

  /** 
  * journals
  * @param journals List&lt;Journal&gt; 
  **/

  public void setJournals(List<Journal> journals) {
    this.journals = journals;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Journals journals = (Journals) o;
    return Objects.equals(this.warnings, journals.warnings) &&
        Objects.equals(this.journals, journals.journals);
  }

  @Override
  public int hashCode() {
    return Objects.hash(warnings, journals);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Journals {\n");
    sb.append("    warnings: ").append(toIndentedString(warnings)).append("\n");
    sb.append("    journals: ").append(toIndentedString(journals)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

