/*
 * Accounting API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.4
 * Contact: api@xero.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.xero.models.accounting;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

import com.xero.api.StringUtil;

/** Journals */
public class Journals {
  StringUtil util = new StringUtil();

  @JsonProperty("Journals")
  private List<Journal> journals = new ArrayList<Journal>();

  public Journals journals(List<Journal> journals) {
    this.journals = journals;
    return this;
  }

  public Journals addJournalsItem(Journal journalsItem) {
    if (this.journals == null) {
      this.journals = new ArrayList<Journal>();
    }
    this.journals.add(journalsItem);
    return this;
  }

  /**
   * Get journals
   *
   * @return journals
   */
  @ApiModelProperty(value = "")
  public List<Journal> getJournals() {
    return journals;
  }

  public void setJournals(List<Journal> journals) {
    this.journals = journals;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Journals journals = (Journals) o;
    return Objects.equals(this.journals, journals.journals);
  }

  @Override
  public int hashCode() {
    return Objects.hash(journals);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Journals {\n");
    sb.append("    journals: ").append(toIndentedString(journals)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
