/*
 * Xero Payroll UK
 * This is the Xero Payroll API for orgs in the UK region.
 *
 * Contact: api@xero.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.xero.models.payrolluk;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/** The employee&#39;s NI Category letter. */
public enum NICategoryLetter {

  /** A */
  A("A"),

  /** B */
  B("B"),

  /** C */
  C("C"),

  /** F */
  F("F"),

  /** H */
  H("H"),

  /** I */
  I("I"),

  /** J */
  J("J"),

  /** L */
  L("L"),

  /** M */
  M("M"),

  /** S */
  S("S"),

  /** V */
  V("V"),

  /** X */
  X("X"),

  /** Z */
  Z("Z"),

  /** D */
  D("D"),

  /** E */
  E("E"),

  /** K */
  K("K"),

  /** N */
  N("N");

  private String value;

  NICategoryLetter(String value) {
    this.value = value;
  }

  /**
   * @return String value
   */
  @JsonValue
  public String getValue() {
    return value;
  }

  /**
   * toString
   *
   * @return String value
   */
  @Override
  public String toString() {
    return String.valueOf(value);
  }

  /**
   * fromValue
   *
   * @param value String
   */
  @JsonCreator
  public static NICategoryLetter fromValue(String value) {
    for (NICategoryLetter b : NICategoryLetter.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}
