/*
 * Xero Finance API
 * The Finance API is a collection of endpoints which customers can use in the course of a loan application, which may assist lenders to gain the confidence they need to provide capital.
 *
 * Contact: api@xero.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.xero.models.finance;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/** Gets or Sets ProblemType */
public enum ProblemType {

  /** NOTSET */
  NOTSET("NotSet"),

  /** BANK_ACCOUNT_NOT_FOUND */
  BANK_ACCOUNT_NOT_FOUND("bank-account-not-found"),

  /** INTERNAL_ERROR */
  INTERNAL_ERROR("internal-error"),

  /** INVALID_APPLICATION */
  INVALID_APPLICATION("invalid-application"),

  /** INVALID_REQUEST */
  INVALID_REQUEST("invalid-request"),

  /** ORGANISATION_NOT_FOUND */
  ORGANISATION_NOT_FOUND("organisation-not-found"),

  /** ORGANISATION_OFFLINE */
  ORGANISATION_OFFLINE("organisation-offline"),

  /** REQUEST_TIMEOUT */
  REQUEST_TIMEOUT("request-timeout"),

  /** SERVICE_UNAVAILABLE */
  SERVICE_UNAVAILABLE("service-unavailable"),

  /** UNAUTHORIZED */
  UNAUTHORIZED("unauthorized"),

  /** RATE_LIMIT_ERROR */
  RATE_LIMIT_ERROR("rate-limit-error");

  private String value;

  ProblemType(String value) {
    this.value = value;
  }

  /** @return String value */
  @JsonValue
  public String getValue() {
    return value;
  }

  /**
   * toString
   *
   * @return String value
   */
  @Override
  public String toString() {
    return String.valueOf(value);
  }

  /**
   * fromValue
   *
   * @param value String
   */
  @JsonCreator
  public static ProblemType fromValue(String value) {
    for (ProblemType b : ProblemType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}
