/*
 * Xero Payroll NZ
 * This is the Xero Payroll API for orgs in the NZ region.
 *
 * Contact: api@xero.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.xero.models.payrollnz;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.xero.api.StringUtil;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;
import org.threeten.bp.LocalDate;

/** EmployeeTax */
public class EmployeeTax {
  StringUtil util = new StringUtil();

  @JsonProperty("irdNumber")
  private String irdNumber;

  @JsonProperty("taxCode")
  private TaxCode taxCode;

  @JsonProperty("specialTaxRatePercentage")
  private Double specialTaxRatePercentage;

  @JsonProperty("hasSpecialStudentLoanRate")
  private Boolean hasSpecialStudentLoanRate;

  @JsonProperty("specialStudentLoanRatePercentage")
  private Double specialStudentLoanRatePercentage;

  @JsonProperty("isEligibleForKiwiSaver")
  private Boolean isEligibleForKiwiSaver;

  @JsonProperty("esctRatePercentage")
  private Double esctRatePercentage;
  /**
   * Contribution Option which can be &#39;MakeContributions&#39; &#39;OptOut&#39;,
   * &#39;OnAContributionsHoliday&#39;, &#39;OnASavingsSuspension&#39;,
   * &#39;NotCurrentlyAKiwiSaverMember&#39; for employees without a KiwiSaver membership
   */
  public enum KiwiSaverContributionsEnum {
    MAKECONTRIBUTIONS("MakeContributions"),

    OPTOUT("OptOut"),

    ONACONTRIBUTIONSHOLIDAY("OnAContributionsHoliday"),

    ONASAVINGSSUSPENSION("OnASavingsSuspension"),

    NOTCURRENTLYAKIWISAVERMEMBER("NotCurrentlyAKiwiSaverMember");

    private String value;

    KiwiSaverContributionsEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static KiwiSaverContributionsEnum fromValue(String value) {
      for (KiwiSaverContributionsEnum b : KiwiSaverContributionsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @JsonProperty("kiwiSaverContributions")
  private KiwiSaverContributionsEnum kiwiSaverContributions;

  @JsonProperty("kiwiSaverEmployeeContributionRatePercentage")
  private Double kiwiSaverEmployeeContributionRatePercentage;

  @JsonProperty("kiwiSaverEmployerContributionRatePercentage")
  private Double kiwiSaverEmployerContributionRatePercentage;

  @JsonProperty("kiwiSaverEmployerSalarySacrificeContributionRatePercentage")
  private Double kiwiSaverEmployerSalarySacrificeContributionRatePercentage;

  @JsonProperty("kiwiSaverOptOutDate")
  private LocalDate kiwiSaverOptOutDate;

  @JsonProperty("kiwiSaverContributionHolidayEndDate")
  private LocalDate kiwiSaverContributionHolidayEndDate;

  @JsonProperty("hasStudentLoanBalance")
  private Boolean hasStudentLoanBalance;

  @JsonProperty("studentLoanBalance")
  private Double studentLoanBalance;

  @JsonProperty("studentLoanAsAt")
  private LocalDate studentLoanAsAt;

  public EmployeeTax irdNumber(String irdNumber) {
    this.irdNumber = irdNumber;
    return this;
  }

  /**
   * The IRD Number.
   *
   * @return irdNumber
   */
  @ApiModelProperty(example = "111111111", value = "The IRD Number.")
  public String getIrdNumber() {
    return irdNumber;
  }

  public void setIrdNumber(String irdNumber) {
    this.irdNumber = irdNumber;
  }

  public EmployeeTax taxCode(TaxCode taxCode) {
    this.taxCode = taxCode;
    return this;
  }

  /**
   * Get taxCode
   *
   * @return taxCode
   */
  @ApiModelProperty(value = "")
  public TaxCode getTaxCode() {
    return taxCode;
  }

  public void setTaxCode(TaxCode taxCode) {
    this.taxCode = taxCode;
  }

  public EmployeeTax specialTaxRatePercentage(Double specialTaxRatePercentage) {
    this.specialTaxRatePercentage = specialTaxRatePercentage;
    return this;
  }

  /**
   * Special tax rate percentage.
   *
   * @return specialTaxRatePercentage
   */
  @ApiModelProperty(example = "17.5", value = "Special tax rate percentage.")
  public Double getSpecialTaxRatePercentage() {
    return specialTaxRatePercentage;
  }

  public void setSpecialTaxRatePercentage(Double specialTaxRatePercentage) {
    this.specialTaxRatePercentage = specialTaxRatePercentage;
  }

  public EmployeeTax hasSpecialStudentLoanRate(Boolean hasSpecialStudentLoanRate) {
    this.hasSpecialStudentLoanRate = hasSpecialStudentLoanRate;
    return this;
  }

  /**
   * Does the employee has a special student loan rate?
   *
   * @return hasSpecialStudentLoanRate
   */
  @ApiModelProperty(example = "true", value = "Does the employee has a special student loan rate?")
  public Boolean getHasSpecialStudentLoanRate() {
    return hasSpecialStudentLoanRate;
  }

  public void setHasSpecialStudentLoanRate(Boolean hasSpecialStudentLoanRate) {
    this.hasSpecialStudentLoanRate = hasSpecialStudentLoanRate;
  }

  public EmployeeTax specialStudentLoanRatePercentage(Double specialStudentLoanRatePercentage) {
    this.specialStudentLoanRatePercentage = specialStudentLoanRatePercentage;
    return this;
  }

  /**
   * The employee student loan rate percentage.
   *
   * @return specialStudentLoanRatePercentage
   */
  @ApiModelProperty(example = "2.0", value = "The employee student loan rate percentage.")
  public Double getSpecialStudentLoanRatePercentage() {
    return specialStudentLoanRatePercentage;
  }

  public void setSpecialStudentLoanRatePercentage(Double specialStudentLoanRatePercentage) {
    this.specialStudentLoanRatePercentage = specialStudentLoanRatePercentage;
  }

  public EmployeeTax isEligibleForKiwiSaver(Boolean isEligibleForKiwiSaver) {
    this.isEligibleForKiwiSaver = isEligibleForKiwiSaver;
    return this;
  }

  /**
   * The employee eligibility for KiwiSaver.
   *
   * @return isEligibleForKiwiSaver
   */
  @ApiModelProperty(example = "true", value = "The employee eligibility for KiwiSaver.")
  public Boolean getIsEligibleForKiwiSaver() {
    return isEligibleForKiwiSaver;
  }

  public void setIsEligibleForKiwiSaver(Boolean isEligibleForKiwiSaver) {
    this.isEligibleForKiwiSaver = isEligibleForKiwiSaver;
  }

  public EmployeeTax esctRatePercentage(Double esctRatePercentage) {
    this.esctRatePercentage = esctRatePercentage;
    return this;
  }

  /**
   * Employer superannuation contribution tax rate.
   *
   * @return esctRatePercentage
   */
  @ApiModelProperty(example = "1.0", value = "Employer superannuation contribution tax rate.")
  public Double getEsctRatePercentage() {
    return esctRatePercentage;
  }

  public void setEsctRatePercentage(Double esctRatePercentage) {
    this.esctRatePercentage = esctRatePercentage;
  }

  public EmployeeTax kiwiSaverContributions(KiwiSaverContributionsEnum kiwiSaverContributions) {
    this.kiwiSaverContributions = kiwiSaverContributions;
    return this;
  }

  /**
   * Contribution Option which can be &#39;MakeContributions&#39; &#39;OptOut&#39;,
   * &#39;OnAContributionsHoliday&#39;, &#39;OnASavingsSuspension&#39;,
   * &#39;NotCurrentlyAKiwiSaverMember&#39; for employees without a KiwiSaver membership
   *
   * @return kiwiSaverContributions
   */
  @ApiModelProperty(
      example = "MakeContributions",
      value =
          "Contribution Option which can be 'MakeContributions' 'OptOut',"
              + " 'OnAContributionsHoliday', 'OnASavingsSuspension',"
              + " 'NotCurrentlyAKiwiSaverMember' for employees without a KiwiSaver membership")
  public KiwiSaverContributionsEnum getKiwiSaverContributions() {
    return kiwiSaverContributions;
  }

  public void setKiwiSaverContributions(KiwiSaverContributionsEnum kiwiSaverContributions) {
    this.kiwiSaverContributions = kiwiSaverContributions;
  }

  public EmployeeTax kiwiSaverEmployeeContributionRatePercentage(
      Double kiwiSaverEmployeeContributionRatePercentage) {
    this.kiwiSaverEmployeeContributionRatePercentage = kiwiSaverEmployeeContributionRatePercentage;
    return this;
  }

  /**
   * Employee Contribution percentage.
   *
   * @return kiwiSaverEmployeeContributionRatePercentage
   */
  @ApiModelProperty(example = "4.0", value = "Employee Contribution percentage.")
  public Double getKiwiSaverEmployeeContributionRatePercentage() {
    return kiwiSaverEmployeeContributionRatePercentage;
  }

  public void setKiwiSaverEmployeeContributionRatePercentage(
      Double kiwiSaverEmployeeContributionRatePercentage) {
    this.kiwiSaverEmployeeContributionRatePercentage = kiwiSaverEmployeeContributionRatePercentage;
  }

  public EmployeeTax kiwiSaverEmployerContributionRatePercentage(
      Double kiwiSaverEmployerContributionRatePercentage) {
    this.kiwiSaverEmployerContributionRatePercentage = kiwiSaverEmployerContributionRatePercentage;
    return this;
  }

  /**
   * Employer Contribution percentage.
   *
   * @return kiwiSaverEmployerContributionRatePercentage
   */
  @ApiModelProperty(example = "10.0", value = "Employer Contribution percentage.")
  public Double getKiwiSaverEmployerContributionRatePercentage() {
    return kiwiSaverEmployerContributionRatePercentage;
  }

  public void setKiwiSaverEmployerContributionRatePercentage(
      Double kiwiSaverEmployerContributionRatePercentage) {
    this.kiwiSaverEmployerContributionRatePercentage = kiwiSaverEmployerContributionRatePercentage;
  }

  public EmployeeTax kiwiSaverEmployerSalarySacrificeContributionRatePercentage(
      Double kiwiSaverEmployerSalarySacrificeContributionRatePercentage) {
    this.kiwiSaverEmployerSalarySacrificeContributionRatePercentage =
        kiwiSaverEmployerSalarySacrificeContributionRatePercentage;
    return this;
  }

  /**
   * Employer Contribution through Salary Sacrifice percentage.
   *
   * @return kiwiSaverEmployerSalarySacrificeContributionRatePercentage
   */
  @ApiModelProperty(
      example = "2.0",
      value = "Employer Contribution through Salary Sacrifice percentage.")
  public Double getKiwiSaverEmployerSalarySacrificeContributionRatePercentage() {
    return kiwiSaverEmployerSalarySacrificeContributionRatePercentage;
  }

  public void setKiwiSaverEmployerSalarySacrificeContributionRatePercentage(
      Double kiwiSaverEmployerSalarySacrificeContributionRatePercentage) {
    this.kiwiSaverEmployerSalarySacrificeContributionRatePercentage =
        kiwiSaverEmployerSalarySacrificeContributionRatePercentage;
  }

  public EmployeeTax kiwiSaverOptOutDate(LocalDate kiwiSaverOptOutDate) {
    this.kiwiSaverOptOutDate = kiwiSaverOptOutDate;
    return this;
  }

  /**
   * Opt Out Date.
   *
   * @return kiwiSaverOptOutDate
   */
  @ApiModelProperty(value = "Opt Out Date.")
  public LocalDate getKiwiSaverOptOutDate() {
    return kiwiSaverOptOutDate;
  }

  public void setKiwiSaverOptOutDate(LocalDate kiwiSaverOptOutDate) {
    this.kiwiSaverOptOutDate = kiwiSaverOptOutDate;
  }

  public EmployeeTax kiwiSaverContributionHolidayEndDate(
      LocalDate kiwiSaverContributionHolidayEndDate) {
    this.kiwiSaverContributionHolidayEndDate = kiwiSaverContributionHolidayEndDate;
    return this;
  }

  /**
   * Contribution holiday expiry date or end date.
   *
   * @return kiwiSaverContributionHolidayEndDate
   */
  @ApiModelProperty(value = "Contribution holiday expiry date or end date.")
  public LocalDate getKiwiSaverContributionHolidayEndDate() {
    return kiwiSaverContributionHolidayEndDate;
  }

  public void setKiwiSaverContributionHolidayEndDate(
      LocalDate kiwiSaverContributionHolidayEndDate) {
    this.kiwiSaverContributionHolidayEndDate = kiwiSaverContributionHolidayEndDate;
  }

  public EmployeeTax hasStudentLoanBalance(Boolean hasStudentLoanBalance) {
    this.hasStudentLoanBalance = hasStudentLoanBalance;
    return this;
  }

  /**
   * Does the employee have a remaining student loan balance? Set a remaining balance if you have
   * received a letter from IR.
   *
   * @return hasStudentLoanBalance
   */
  @ApiModelProperty(
      example = "false",
      value =
          "Does the employee have a remaining student loan balance? Set a remaining balance if you"
              + " have received a letter from IR.")
  public Boolean getHasStudentLoanBalance() {
    return hasStudentLoanBalance;
  }

  public void setHasStudentLoanBalance(Boolean hasStudentLoanBalance) {
    this.hasStudentLoanBalance = hasStudentLoanBalance;
  }

  public EmployeeTax studentLoanBalance(Double studentLoanBalance) {
    this.studentLoanBalance = studentLoanBalance;
    return this;
  }

  /**
   * The employee&#39;s student loan balance shown on the letter from IR.
   *
   * @return studentLoanBalance
   */
  @ApiModelProperty(
      example = "30.0",
      value = "The employee's student loan balance shown on the letter from IR.")
  public Double getStudentLoanBalance() {
    return studentLoanBalance;
  }

  public void setStudentLoanBalance(Double studentLoanBalance) {
    this.studentLoanBalance = studentLoanBalance;
  }

  public EmployeeTax studentLoanAsAt(LocalDate studentLoanAsAt) {
    this.studentLoanAsAt = studentLoanAsAt;
    return this;
  }

  /**
   * The date of the letter from IR.
   *
   * @return studentLoanAsAt
   */
  @ApiModelProperty(value = "The date of the letter from IR.")
  public LocalDate getStudentLoanAsAt() {
    return studentLoanAsAt;
  }

  public void setStudentLoanAsAt(LocalDate studentLoanAsAt) {
    this.studentLoanAsAt = studentLoanAsAt;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmployeeTax employeeTax = (EmployeeTax) o;
    return Objects.equals(this.irdNumber, employeeTax.irdNumber)
        && Objects.equals(this.taxCode, employeeTax.taxCode)
        && Objects.equals(this.specialTaxRatePercentage, employeeTax.specialTaxRatePercentage)
        && Objects.equals(this.hasSpecialStudentLoanRate, employeeTax.hasSpecialStudentLoanRate)
        && Objects.equals(
            this.specialStudentLoanRatePercentage, employeeTax.specialStudentLoanRatePercentage)
        && Objects.equals(this.isEligibleForKiwiSaver, employeeTax.isEligibleForKiwiSaver)
        && Objects.equals(this.esctRatePercentage, employeeTax.esctRatePercentage)
        && Objects.equals(this.kiwiSaverContributions, employeeTax.kiwiSaverContributions)
        && Objects.equals(
            this.kiwiSaverEmployeeContributionRatePercentage,
            employeeTax.kiwiSaverEmployeeContributionRatePercentage)
        && Objects.equals(
            this.kiwiSaverEmployerContributionRatePercentage,
            employeeTax.kiwiSaverEmployerContributionRatePercentage)
        && Objects.equals(
            this.kiwiSaverEmployerSalarySacrificeContributionRatePercentage,
            employeeTax.kiwiSaverEmployerSalarySacrificeContributionRatePercentage)
        && Objects.equals(this.kiwiSaverOptOutDate, employeeTax.kiwiSaverOptOutDate)
        && Objects.equals(
            this.kiwiSaverContributionHolidayEndDate,
            employeeTax.kiwiSaverContributionHolidayEndDate)
        && Objects.equals(this.hasStudentLoanBalance, employeeTax.hasStudentLoanBalance)
        && Objects.equals(this.studentLoanBalance, employeeTax.studentLoanBalance)
        && Objects.equals(this.studentLoanAsAt, employeeTax.studentLoanAsAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        irdNumber,
        taxCode,
        specialTaxRatePercentage,
        hasSpecialStudentLoanRate,
        specialStudentLoanRatePercentage,
        isEligibleForKiwiSaver,
        esctRatePercentage,
        kiwiSaverContributions,
        kiwiSaverEmployeeContributionRatePercentage,
        kiwiSaverEmployerContributionRatePercentage,
        kiwiSaverEmployerSalarySacrificeContributionRatePercentage,
        kiwiSaverOptOutDate,
        kiwiSaverContributionHolidayEndDate,
        hasStudentLoanBalance,
        studentLoanBalance,
        studentLoanAsAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmployeeTax {\n");
    sb.append("    irdNumber: ").append(toIndentedString(irdNumber)).append("\n");
    sb.append("    taxCode: ").append(toIndentedString(taxCode)).append("\n");
    sb.append("    specialTaxRatePercentage: ")
        .append(toIndentedString(specialTaxRatePercentage))
        .append("\n");
    sb.append("    hasSpecialStudentLoanRate: ")
        .append(toIndentedString(hasSpecialStudentLoanRate))
        .append("\n");
    sb.append("    specialStudentLoanRatePercentage: ")
        .append(toIndentedString(specialStudentLoanRatePercentage))
        .append("\n");
    sb.append("    isEligibleForKiwiSaver: ")
        .append(toIndentedString(isEligibleForKiwiSaver))
        .append("\n");
    sb.append("    esctRatePercentage: ").append(toIndentedString(esctRatePercentage)).append("\n");
    sb.append("    kiwiSaverContributions: ")
        .append(toIndentedString(kiwiSaverContributions))
        .append("\n");
    sb.append("    kiwiSaverEmployeeContributionRatePercentage: ")
        .append(toIndentedString(kiwiSaverEmployeeContributionRatePercentage))
        .append("\n");
    sb.append("    kiwiSaverEmployerContributionRatePercentage: ")
        .append(toIndentedString(kiwiSaverEmployerContributionRatePercentage))
        .append("\n");
    sb.append("    kiwiSaverEmployerSalarySacrificeContributionRatePercentage: ")
        .append(toIndentedString(kiwiSaverEmployerSalarySacrificeContributionRatePercentage))
        .append("\n");
    sb.append("    kiwiSaverOptOutDate: ")
        .append(toIndentedString(kiwiSaverOptOutDate))
        .append("\n");
    sb.append("    kiwiSaverContributionHolidayEndDate: ")
        .append(toIndentedString(kiwiSaverContributionHolidayEndDate))
        .append("\n");
    sb.append("    hasStudentLoanBalance: ")
        .append(toIndentedString(hasStudentLoanBalance))
        .append("\n");
    sb.append("    studentLoanBalance: ").append(toIndentedString(studentLoanBalance)).append("\n");
    sb.append("    studentLoanAsAt: ").append(toIndentedString(studentLoanAsAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
