/*
 * Xero Payroll NZ
 * This is the Xero Payroll API for orgs in the NZ region.
 *
 * Contact: api@xero.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.xero.models.payrollnz;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.xero.api.StringUtil;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/** TimesheetObject */
public class TimesheetObject {
  StringUtil util = new StringUtil();

  @JsonProperty("pagination")
  private Pagination pagination;

  @JsonProperty("problem")
  private Problem problem;

  @JsonProperty("timesheet")
  private Timesheet timesheet;
  /**
   * pagination
   *
   * @param pagination Pagination
   * @return TimesheetObject
   */
  public TimesheetObject pagination(Pagination pagination) {
    this.pagination = pagination;
    return this;
  }

  /**
   * Get pagination
   *
   * @return pagination
   */
  @ApiModelProperty(value = "")
  /**
   * pagination
   *
   * @return pagination Pagination
   */
  public Pagination getPagination() {
    return pagination;
  }

  /**
   * pagination
   *
   * @param pagination Pagination
   */
  public void setPagination(Pagination pagination) {
    this.pagination = pagination;
  }

  /**
   * problem
   *
   * @param problem Problem
   * @return TimesheetObject
   */
  public TimesheetObject problem(Problem problem) {
    this.problem = problem;
    return this;
  }

  /**
   * Get problem
   *
   * @return problem
   */
  @ApiModelProperty(value = "")
  /**
   * problem
   *
   * @return problem Problem
   */
  public Problem getProblem() {
    return problem;
  }

  /**
   * problem
   *
   * @param problem Problem
   */
  public void setProblem(Problem problem) {
    this.problem = problem;
  }

  /**
   * timesheet
   *
   * @param timesheet Timesheet
   * @return TimesheetObject
   */
  public TimesheetObject timesheet(Timesheet timesheet) {
    this.timesheet = timesheet;
    return this;
  }

  /**
   * Get timesheet
   *
   * @return timesheet
   */
  @ApiModelProperty(value = "")
  /**
   * timesheet
   *
   * @return timesheet Timesheet
   */
  public Timesheet getTimesheet() {
    return timesheet;
  }

  /**
   * timesheet
   *
   * @param timesheet Timesheet
   */
  public void setTimesheet(Timesheet timesheet) {
    this.timesheet = timesheet;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimesheetObject timesheetObject = (TimesheetObject) o;
    return Objects.equals(this.pagination, timesheetObject.pagination)
        && Objects.equals(this.problem, timesheetObject.problem)
        && Objects.equals(this.timesheet, timesheetObject.timesheet);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pagination, problem, timesheet);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimesheetObject {\n");
    sb.append("    pagination: ").append(toIndentedString(pagination)).append("\n");
    sb.append("    problem: ").append(toIndentedString(problem)).append("\n");
    sb.append("    timesheet: ").append(toIndentedString(timesheet)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
