/*
 * Xero Payroll AU
 * This is the Xero Payroll API for orgs in Australia region.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@xero.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.xero.models.payrollau;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * DeductionType
 */

public class DeductionType {
  
  @JsonProperty("Name")
  private String name;

  
  @JsonProperty("AccountCode")
  private String accountCode;

  
  @JsonProperty("ReducesTax")
  private Boolean reducesTax;

  
  @JsonProperty("ReducesSuper")
  private Boolean reducesSuper;

  
  @JsonProperty("IsExemptFromW1")
  private Boolean isExemptFromW1;

  
  @JsonProperty("DeductionTypeID")
  private UUID deductionTypeID;

  @JsonDeserialize(using = com.xero.api.CustomOffsetDateTimeDeserializer.class)
  @JsonProperty("UpdatedDateUTC")
  private OffsetDateTime updatedDateUTC;

  public DeductionType name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the earnings rate (max length &#x3D; 100)
   * @return name
  **/
  @ApiModelProperty(example = "PTO", value = "Name of the earnings rate (max length = 100)")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public DeductionType accountCode(String accountCode) {
    this.accountCode = accountCode;
    return this;
  }

   /**
   * See Accounts
   * @return accountCode
  **/
  @ApiModelProperty(example = "720", value = "See Accounts")
  public String getAccountCode() {
    return accountCode;
  }

  public void setAccountCode(String accountCode) {
    this.accountCode = accountCode;
  }

  public DeductionType reducesTax(Boolean reducesTax) {
    this.reducesTax = reducesTax;
    return this;
  }

   /**
   * Indicates that this is a pre-tax deduction that will reduce the amount of tax you withhold from an employee.
   * @return reducesTax
  **/
  @ApiModelProperty(example = "false", value = "Indicates that this is a pre-tax deduction that will reduce the amount of tax you withhold from an employee.")
  public Boolean getReducesTax() {
    return reducesTax;
  }

  public void setReducesTax(Boolean reducesTax) {
    this.reducesTax = reducesTax;
  }

  public DeductionType reducesSuper(Boolean reducesSuper) {
    this.reducesSuper = reducesSuper;
    return this;
  }

   /**
   * Most deductions don’t reduce your superannuation guarantee contribution liability, so typically you will not set any value for this.
   * @return reducesSuper
  **/
  @ApiModelProperty(example = "false", value = "Most deductions don’t reduce your superannuation guarantee contribution liability, so typically you will not set any value for this.")
  public Boolean getReducesSuper() {
    return reducesSuper;
  }

  public void setReducesSuper(Boolean reducesSuper) {
    this.reducesSuper = reducesSuper;
  }

  public DeductionType isExemptFromW1(Boolean isExemptFromW1) {
    this.isExemptFromW1 = isExemptFromW1;
    return this;
  }

   /**
   * Boolean to determine if the deduction type is reportable or exempt from W1
   * @return isExemptFromW1
  **/
  @ApiModelProperty(example = "false", value = "Boolean to determine if the deduction type is reportable or exempt from W1")
  public Boolean getIsExemptFromW1() {
    return isExemptFromW1;
  }

  public void setIsExemptFromW1(Boolean isExemptFromW1) {
    this.isExemptFromW1 = isExemptFromW1;
  }

  public DeductionType deductionTypeID(UUID deductionTypeID) {
    this.deductionTypeID = deductionTypeID;
    return this;
  }

   /**
   * Xero identifier
   * @return deductionTypeID
  **/
  @ApiModelProperty(example = "e0eb6747-7c17-4075-b804-989f8d4e5d39", value = "Xero identifier")
  public UUID getDeductionTypeID() {
    return deductionTypeID;
  }

  public void setDeductionTypeID(UUID deductionTypeID) {
    this.deductionTypeID = deductionTypeID;
  }

  public DeductionType updatedDateUTC(OffsetDateTime updatedDateUTC) {
    this.updatedDateUTC = updatedDateUTC;
    return this;
  }

   /**
   * Last modified timestamp
   * @return updatedDateUTC
  **/
  @ApiModelProperty(value = "Last modified timestamp")
  public OffsetDateTime getUpdatedDateUTC() {
    return updatedDateUTC;
  }

  public void setUpdatedDateUTC(OffsetDateTime updatedDateUTC) {
    this.updatedDateUTC = updatedDateUTC;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeductionType deductionType = (DeductionType) o;
    return Objects.equals(this.name, deductionType.name) &&
        Objects.equals(this.accountCode, deductionType.accountCode) &&
        Objects.equals(this.reducesTax, deductionType.reducesTax) &&
        Objects.equals(this.reducesSuper, deductionType.reducesSuper) &&
        Objects.equals(this.isExemptFromW1, deductionType.isExemptFromW1) &&
        Objects.equals(this.deductionTypeID, deductionType.deductionTypeID) &&
        Objects.equals(this.updatedDateUTC, deductionType.updatedDateUTC);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, accountCode, reducesTax, reducesSuper, isExemptFromW1, deductionTypeID, updatedDateUTC);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeductionType {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    accountCode: ").append(toIndentedString(accountCode)).append("\n");
    sb.append("    reducesTax: ").append(toIndentedString(reducesTax)).append("\n");
    sb.append("    reducesSuper: ").append(toIndentedString(reducesSuper)).append("\n");
    sb.append("    isExemptFromW1: ").append(toIndentedString(isExemptFromW1)).append("\n");
    sb.append("    deductionTypeID: ").append(toIndentedString(deductionTypeID)).append("\n");
    sb.append("    updatedDateUTC: ").append(toIndentedString(updatedDateUTC)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

