/*
 * Xero Payroll AU
 * This is the Xero Payroll API for orgs in Australia region.
 *
 * The version of the OpenAPI document: 2.2.4
 * Contact: api@xero.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.xero.models.payrollau;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import com.xero.api.StringUtil;

/** PayItems */
public class PayItems {
  StringUtil util = new StringUtil();

  @JsonProperty("PayItems")
  private PayItem payItems;

  public PayItems payItems(PayItem payItems) {
    this.payItems = payItems;
    return this;
  }

  /**
   * Get payItems
   *
   * @return payItems
   */
  @ApiModelProperty(value = "")
  public PayItem getPayItems() {
    return payItems;
  }

  public void setPayItems(PayItem payItems) {
    this.payItems = payItems;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PayItems payItems = (PayItems) o;
    return Objects.equals(this.payItems, payItems.payItems);
  }

  @Override
  public int hashCode() {
    return Objects.hash(payItems);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PayItems {\n");
    sb.append("    payItems: ").append(toIndentedString(payItems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
