/*
 * Xero Payroll AU
 * This is the Xero Payroll API for orgs in Australia region.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@xero.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.xero.models.payrollau;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * PayslipSummary
 */

public class PayslipSummary {
  
  @JsonProperty("EmployeeID")
  private Object employeeID = null;

  
  @JsonProperty("PayslipID")
  private Object payslipID = null;

  
  @JsonProperty("FirstName")
  private String firstName;

  
  @JsonProperty("LastName")
  private String lastName;

  
  @JsonProperty("Wages")
  private Float wages;

  
  @JsonProperty("Deductions")
  private Float deductions;

  
  @JsonProperty("Tax")
  private Float tax;

  
  @JsonProperty("Super")
  private Float _super;

  
  @JsonProperty("Reimbursements")
  private Float reimbursements;

  
  @JsonProperty("NetPay")
  private Float netPay;

  @JsonDeserialize(using = com.xero.api.CustomOffsetDateTimeDeserializer.class)
  @JsonProperty("UpdatedDateUTC")
  private OffsetDateTime updatedDateUTC;

  public PayslipSummary employeeID(Object employeeID) {
    this.employeeID = employeeID;
    return this;
  }

   /**
   * The Xero identifier for an employee
   * @return employeeID
  **/
  @ApiModelProperty(example = "4729f087-8eec-49c1-8294-4d11a5a0a37c", value = "The Xero identifier for an employee")
  public Object getEmployeeID() {
    return employeeID;
  }

  public void setEmployeeID(Object employeeID) {
    this.employeeID = employeeID;
  }

  public PayslipSummary payslipID(Object payslipID) {
    this.payslipID = payslipID;
    return this;
  }

   /**
   * Xero identifier for the payslip
   * @return payslipID
  **/
  @ApiModelProperty(example = "f3c0874d-7cdd-459a-a95c-d90d51decc42", value = "Xero identifier for the payslip")
  public Object getPayslipID() {
    return payslipID;
  }

  public void setPayslipID(Object payslipID) {
    this.payslipID = payslipID;
  }

  public PayslipSummary firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * First name of employee
   * @return firstName
  **/
  @ApiModelProperty(example = "Karen", value = "First name of employee")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public PayslipSummary lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Last name of employee
   * @return lastName
  **/
  @ApiModelProperty(example = "Jones", value = "Last name of employee")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public PayslipSummary wages(Float wages) {
    this.wages = wages;
    return this;
  }

   /**
   * The Wages for the Payslip
   * @return wages
  **/
  @ApiModelProperty(example = "1060.5", value = "The Wages for the Payslip")
  public Float getWages() {
    return wages;
  }

  public void setWages(Float wages) {
    this.wages = wages;
  }

  public PayslipSummary deductions(Float deductions) {
    this.deductions = deductions;
    return this;
  }

   /**
   * The Deductions for the Payslip
   * @return deductions
  **/
  @ApiModelProperty(example = "0.0", value = "The Deductions for the Payslip")
  public Float getDeductions() {
    return deductions;
  }

  public void setDeductions(Float deductions) {
    this.deductions = deductions;
  }

  public PayslipSummary tax(Float tax) {
    this.tax = tax;
    return this;
  }

   /**
   * The Tax for the Payslip
   * @return tax
  **/
  @ApiModelProperty(example = "198.0", value = "The Tax for the Payslip")
  public Float getTax() {
    return tax;
  }

  public void setTax(Float tax) {
    this.tax = tax;
  }

  public PayslipSummary _super(Float _super) {
    this._super = _super;
    return this;
  }

   /**
   * The Super for the Payslip
   * @return _super
  **/
  @ApiModelProperty(example = "75.6", value = "The Super for the Payslip")
  public Float getSuper() {
    return _super;
  }

  public void setSuper(Float _super) {
    this._super = _super;
  }

  public PayslipSummary reimbursements(Float reimbursements) {
    this.reimbursements = reimbursements;
    return this;
  }

   /**
   * The Reimbursements for the Payslip
   * @return reimbursements
  **/
  @ApiModelProperty(example = "0.0", value = "The Reimbursements for the Payslip")
  public Float getReimbursements() {
    return reimbursements;
  }

  public void setReimbursements(Float reimbursements) {
    this.reimbursements = reimbursements;
  }

  public PayslipSummary netPay(Float netPay) {
    this.netPay = netPay;
    return this;
  }

   /**
   * The NetPay for the Payslip
   * @return netPay
  **/
  @ApiModelProperty(example = "862.5", value = "The NetPay for the Payslip")
  public Float getNetPay() {
    return netPay;
  }

  public void setNetPay(Float netPay) {
    this.netPay = netPay;
  }

  public PayslipSummary updatedDateUTC(OffsetDateTime updatedDateUTC) {
    this.updatedDateUTC = updatedDateUTC;
    return this;
  }

   /**
   * Last modified timestamp
   * @return updatedDateUTC
  **/
  @ApiModelProperty(value = "Last modified timestamp")
  public OffsetDateTime getUpdatedDateUTC() {
    return updatedDateUTC;
  }

  public void setUpdatedDateUTC(OffsetDateTime updatedDateUTC) {
    this.updatedDateUTC = updatedDateUTC;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PayslipSummary payslipSummary = (PayslipSummary) o;
    return Objects.equals(this.employeeID, payslipSummary.employeeID) &&
        Objects.equals(this.payslipID, payslipSummary.payslipID) &&
        Objects.equals(this.firstName, payslipSummary.firstName) &&
        Objects.equals(this.lastName, payslipSummary.lastName) &&
        Objects.equals(this.wages, payslipSummary.wages) &&
        Objects.equals(this.deductions, payslipSummary.deductions) &&
        Objects.equals(this.tax, payslipSummary.tax) &&
        Objects.equals(this._super, payslipSummary._super) &&
        Objects.equals(this.reimbursements, payslipSummary.reimbursements) &&
        Objects.equals(this.netPay, payslipSummary.netPay) &&
        Objects.equals(this.updatedDateUTC, payslipSummary.updatedDateUTC);
  }

  @Override
  public int hashCode() {
    return Objects.hash(employeeID, payslipID, firstName, lastName, wages, deductions, tax, _super, reimbursements, netPay, updatedDateUTC);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PayslipSummary {\n");
    sb.append("    employeeID: ").append(toIndentedString(employeeID)).append("\n");
    sb.append("    payslipID: ").append(toIndentedString(payslipID)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    wages: ").append(toIndentedString(wages)).append("\n");
    sb.append("    deductions: ").append(toIndentedString(deductions)).append("\n");
    sb.append("    tax: ").append(toIndentedString(tax)).append("\n");
    sb.append("    _super: ").append(toIndentedString(_super)).append("\n");
    sb.append("    reimbursements: ").append(toIndentedString(reimbursements)).append("\n");
    sb.append("    netPay: ").append(toIndentedString(netPay)).append("\n");
    sb.append("    updatedDateUTC: ").append(toIndentedString(updatedDateUTC)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

