name: Publish
on:
    push:
    release:
        types: [published]

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Xero-Java repo
              uses: actions/checkout@v4
              with:
                repository: XeroAPI/Xero-Java
                path: Xero-Java

            - name: Set up JDK environment
              uses: actions/setup-java@v4
              with: 
                distribution: 'temurin'
                java-version: '11'
                cache: maven
                server-id: ossrh
                server-username: MAVEN_USERNAME
                server-password: MAVEN_PASSWORD
                gpg-passphrase: GPG_PASSPHRASE

            - name: Import GPG Key
              run: |
                echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
              env: 
                GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY}}

            - name: Publish to Maven
              run: |
                export GPG_TTY=$(tty)
                mvn clean deploy -DskipTests=true
              env:
                MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
                MAVEN_PASSWORD: ${{ secrets.MAVEN_TOKEN }}
                GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
              working-directory: Xero-Java
