name: Publish
on:
    push:
    release:
        types: [published]

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Xero-Java repo
              uses: actions/checkout@v4
              with:
                repository: XeroAPI/Xero-Java
                path: Xero-Java

            - name: Set up JDK environment
              uses: actions/setup-java@v4
              with: 
                distribution: 'temurin'
                java-version: '11'
                cache: maven

            - name: Import GPG Key
              run: |
                echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
              env: 
                GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY}}

            - name: Configure Maven settings
              run: |
                mkdir -p ~/.m2
                echo "<settings>
                        <servers>
                            <server>
                              <id>ossrh</id>
                              <username>${{ secrets.MAVEN_USERNAME }}</username>
                              <password>${{ secrets.MAVEN_TOKEN }}</password>
                            </server>
                          </servers>
                        </settings>" > ~/.m2/settings.xml

            - name: Publish to Maven
              run: |
                export GPG_TTY=$(tty)
                mvn clean deploy -DskipTests=true -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
              working-directory: Xero-Java
